name: Criar Conta Temporária

on:
  repository_dispatch:
    types: [create_temp_account]

jobs:
  criar-conta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with: { python-version: '3.x' }

      - name: Atualizar accounts.json
        run: |
          python -c "
          import json, datetime
          with open('accounts.json', 'r') as f:
              data = json.load(f)
          main_account = next(acc for acc in data['contas_principais'] if acc['username'] == '${{ github.event.client_payload.main_username }}')
          temp_user = f'{main_account["username"]}_temp_{datetime.datetime.now().timestamp()}'
          temp_pass = 'temp_' + datetime.datetime.now().strftime('%H%M%S')
          expiration = datetime.datetime.now() + datetime.timedelta(hours=${{ github.event.client_payload.hours }})
          main_account['temporarias'].append({
              'username': temp_user,
              'password': temp_pass,
              'expira_em': expiration.isoformat()
          })
          with open('accounts.json', 'w') as f:
              json.dump(data, f, indent=2)
          "

      - name: Commit e Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add accounts.json
          git commit -m "Adiciona conta temporária"
          git push
