name: Criar Conta IPTV

on:
  repository_dispatch:
    types: [create_temp_account]

jobs:
  criar-conta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gerar Nova Conta
        run: |
          if [ ! -f accounts.json ]; then echo '[]' > accounts.json; fi
          python -c "
          import json, datetime, uuid, os
          with open('accounts.json', 'r') as f:
              contas = json.load(f)
          nova_conta = {
              'id': str(uuid.uuid4()),
              'username': f'user_${datetime.datetime.now().strftime('%Y%m%d%H%M%S')}',
              'password': 'temp_' + os.urandom(4).hex(),
              'expires_at': (datetime.datetime.now() + datetime.timedelta(hours=2)).isoformat()
          }
          contas.append(nova_conta)
          with open('accounts.json', 'w') as f:
              json.dump(contas, f, indent=2)
          "
      - name: Commit e Push
        run: |
          git config --global user.name "pnetv22 Bot"
          git config --global user.email "actions@pnetv22.github.io"
          git add accounts.json
          git commit -m "Adiciona conta temporária"
          git push
