name: Excluir Conta IPTV

on:
  repository_dispatch:
    types: [delete_temp_account]

jobs:
  excluir-conta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remover Conta
        run: |
          python -c "
          import json, os
          with open('accounts.json', 'r') as f:
              contas = json.load(f)
          contas = [c for c in contas if c['id'] != os.environ['INPUT_ID']]
          with open('accounts.json', 'w') as f:
              json.dump(contas, f, indent=2)
          "
        env:
          INPUT_ID: ${{ github.event.client_payload.id }}
      - name: Commit e Push
        run: |
          git config --global user.name "pnetv22 Bot"
          git config --global user.email "actions@pnetv22.github.io"
          git add accounts.json
          git commit -m "Remove conta temporária"
          git push
